// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCX9aJo25MDrTgtJ6b6oywbfONBhsNvQQ',
    appId: '1:435316737616:web:948782743c095e840af355',
    messagingSenderId: '435316737616',
    projectId: 'temperature-sensor-software',
    authDomain: 'temperature-sensor-software.firebaseapp.com',
    storageBucket: 'temperature-sensor-software.firebasestorage.app',
    measurementId: 'G-7TFS826854',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgr4ifioIPaM2BVhq3SXAMSiAwCv8Xnow',
    appId: '1:435316737616:android:171651af14d5a6940af355',
    messagingSenderId: '435316737616',
    projectId: 'temperature-sensor-software',
    storageBucket: 'temperature-sensor-software.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAsIudpM8NtJ0tNjt-6031pqNakvZ-og',
    appId: '1:435316737616:ios:b4c9a6f4c2ae7e7d0af355',
    messagingSenderId: '435316737616',
    projectId: 'temperature-sensor-software',
    storageBucket: 'temperature-sensor-software.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACAsIudpM8NtJ0tNjt-6031pqNakvZ-og',
    appId: '1:435316737616:ios:b4c9a6f4c2ae7e7d0af355',
    messagingSenderId: '435316737616',
    projectId: 'temperature-sensor-software',
    storageBucket: 'temperature-sensor-software.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCX9aJo25MDrTgtJ6b6oywbfONBhsNvQQ',
    appId: '1:435316737616:web:007a7c5c053b41b10af355',
    messagingSenderId: '435316737616',
    projectId: 'temperature-sensor-software',
    authDomain: 'temperature-sensor-software.firebaseapp.com',
    storageBucket: 'temperature-sensor-software.firebasestorage.app',
    measurementId: 'G-KMP6S09VKT',
  );
}
